version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
