#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd api

echo "Checking API"
npm run prettier
npm run lint
npm run test

cd ..
cd worker
echo "Checking WORKER"

npm run prettier
npm run lint
npm run test

