#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd api

if [[ `git status --porcelain` ]]; then
    echo "Checking API"
    npm run prettier
    npm run lint
    npm run test
fi

cd ..
cd worker

if [[ `git status --porcelain` ]]; then
    echo "Checking WORKER"
    npm run prettier
    npm run lint
    npm run test
fi

