#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ `git status --porcelain api` ]]; then
    cd api
    echo "Checking API"
    npm run prettier
    npm run lint
    npm run test
    cd ..
fi

if [[ `git status --porcelain worker` ]]; then
    cd worker
    echo "Checking WORKER"
    npm run prettier
    npm run lint
    npm run test
    cd ..
fi

